In [2]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(array)

NameError: name 'array' is not defined

In [5]:
arr = np.arange(0,10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr = np.arange(0,20,2)

In [9]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3).astype(np.int64))

AttributeError: 'int' object has no attribute 'astype'

In [13]:
arr_zeros = np.zeros(3)

In [15]:
arr_zeros = arr.astype(np.int64)

In [16]:
arr_zeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

In [17]:
arr_zeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

In [18]:
arr_zeros = np.zeros(3)

In [19]:
arr_zeros

array([0., 0., 0.])

In [20]:
arr_zeros = arr.astype(np.int64)
arr_zeros

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

In [21]:
np.random.rand()

0.034452771287103334

In [24]:
np.random.randint(3)

1

In [26]:
np.random.rand(4)

array([0.9815916 , 0.25183951, 0.36774619, 0.45742175])

In [27]:
np.random.randint(4)

1

In [28]:
np.random.randint(4,4)

ValueError: low >= high

In [29]:
np.random.rand(4)

array([0.25156478, 0.47320683, 0.48360359, 0.83169563])

In [30]:
np.random.randint(0,10)

6

In [33]:
np.random.randint(0,100,(10,10))

array([[53,  6, 85,  3, 60, 44, 76, 97, 44, 29],
       [37, 26, 50, 30,  2, 90, 34, 29, 94, 50],
       [ 8, 46, 94, 87, 69, 38, 98, 89, 20, 28],
       [82,  1, 39, 70, 68, 21, 16, 52, 84,  3],
       [ 6,  3, 81, 92,  5, 51, 59,  0, 46, 91],
       [96, 98, 81, 14, 38, 79, 40, 21, 39, 20],
       [73, 87, 53, 19, 43, 43, 62, 36, 52, 71],
       [18, 36, 20, 41, 89, 49, 82, 38, 15, 76],
       [49, 82, 50, 80, 14, 17, 11, 85, 67,  9],
       [19, 34, 79, 67, 26, 14, 99, 38, 90, 74]])

In [3]:
arr1 = np.linspace(1,10,10, dtype = 'int8')

In [4]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
arr1 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [7]:
indices_cond = arr1 > 5

In [8]:
arr1[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [9]:
arr1[(arr > 5) & (arr<9)]

NameError: name 'arr' is not defined

In [10]:
arr1[(arr1 > 5) & (arr1<9)]

array([6, 7, 8], dtype=int8)