In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr = np.array([1,2,3,4], dtype='int64')

In [7]:
arr.dtype

dtype('int64')

In [9]:
arr = np.array([1,2,3,4], dtype='float64')

In [10]:
arr.dtype

dtype('float64')

In [11]:
arr

array([1., 2., 3., 4.])

In [12]:
arr.astype(np.int64)

array([1, 2, 3, 4], dtype=int64)

In [13]:
arr

array([1., 2., 3., 4.])

In [14]:
arr = arr.astype(np.int64)

In [15]:
arr

array([1, 2, 3, 4], dtype=int64)

In [16]:
arr = np.array([0,0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False, False,  True,  True,  True,  True])

In [17]:
arr = np.array([0,0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

In [18]:
arr = np.array(['0','0','0','2','3','4'])
arr = arr.astype(np.int64)
arr

array([0, 0, 0, 2, 3, 4], dtype=int64)

In [19]:
arr = np.array(['0','0','1','2','3','4'])
arr = arr.astype(np.int64)
arr

array([0, 0, 1, 2, 3, 4], dtype=int64)