In [1]:
import numpy as np

In [2]:
scalar = np.array([42])
scalar

array([42])

In [3]:
scalar.ndim

1

In [4]:
scalar = np.array(42)
scalar
scalar.ndim

0

In [5]:
vector = np.array([1,2,3])
vector
vector.ndim

1

In [6]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [8]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [19]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [22]:
##Agregar o eliminar Dimensiones

In [23]:
vector = np.array([1,2,3], ndmin=10)

In [26]:
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [28]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [29]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [32]:
tensor1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(tensor1)
tensor1.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


3

In [33]:
tensor1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(tensor1)
tensor1.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


3

In [40]:
tensor_expand = np.expand_dims(np.array([[1,2,3],
  [4,5,6],
  [7,8,9]]), axis=0)
print(tensor_expand)
tensor_expand.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [41]:
print(tensor1)
print(tensor_expand)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [45]:
tensor2 = np.expand_dims(np.array([90,91,92]), axis=1)

In [46]:
tensor2

array([[90],
       [91],
       [92]])

In [48]:
expand = np.expand_dims(tensor1, axis=0)
print(expand)
expand.ndim

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]]


4

In [49]:
tensor_use = np.squeeze(tensor1)
print(tensor_use, tensor.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 3
