In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1 = arr.copy()

In [6]:
arr
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr * 2
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr * 2
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).ndim

2

In [14]:
np.array([1,2,3]).ndim

1

In [16]:
np.array([[1,2,3],[4,5,6]]).ndim

2

In [ ]:
np.array([[1,2,3],[4,5,6]]).ndim