In [2]:
import pandas as pd

In [3]:
df_datos = pd.read_csv('pandas_numpy/Retractos.csv', sep=';' header=0)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3331721320.py, line 1)

In [4]:
df_datos = pd.read_csv('pandas_numpy/Retractos.csv', sep=';', header=0)

In [5]:
df_datos

TIPO_ID   NUMERO_ID     ENTIDAD FECHA_ENVIO_A_MINSALUD  \
0       CC  1108641315  PROTECCION       19/04/2022 16:20   
1       CC  1020415150  PROTECCION       19/04/2022 16:20   
2       CC  1034656349  PROTECCION       19/04/2022 16:20   
3       CC  1032494977  PROTECCION       19/04/2022 16:20   
4       CC  1007522327  PROTECCION       19/04/2022 16:20   
..     ...         ...         ...                    ...   
80      CC  1000565326  PROTECCION       19/04/2022 16:50   
81      CC  1090362152  PROTECCION       19/04/2022 16:50   
82      CC  1004232203  PROTECCION       19/04/2022 16:50   
83      CC  1093295249  PROTECCION       19/04/2022 16:50   
84      CC  1003377334  PROTECCION       19/04/2022 16:50   

                                     REQUEST_MINSALUD  \
0   {fechaSolicitud": "", "numeroRadicadoSolicitud...   
1   {fechaSolicitud": "", "numeroRadicadoSolicitud...   
2   {fechaSolicitud": "", "numeroRadicadoSolicitud...   
3   {fechaSolicitud": "", "numeroRadicadoSolicitud...   
4   {fechaSolicitud": "", "numeroRadicadoSolicitud...   
..                                                ...   
80  {fechaSolicitud": "", "numeroRadicadoSolicitud...   
81  {fechaSolicitud": "", "numeroRadicadoSolicitud...   
82  {fechaSolicitud": "", "numeroRadicadoSolicitud...   
83  {fechaSolicitud": "", "numeroRadicadoSolicitud...   
84  {fechaSolicitud": "", "numeroRadicadoSolicitud...   

                                    RESPONSE_MINSALUD  
0   {codigo": "GN23C", "mensaje": "El número de co...  
1   {codigo": "GN23C", "mensaje": "El número de co...  
2   {codigo": "GN23C", "mensaje": "El número de co...  
3   {codigo": "GN23C", "mensaje": "El número de co...  
4   {codigo": "GN23C", "mensaje": "El número de co...  
..                                                ...  
80  {codigo": "GN23C", "mensaje": "El número de co...  
81  {codigo": "GN23C", "mensaje": "El número de co...  
82  {codigo": "GN23C", "mensaje": "El número de co...  
83  {codigo": "GN23C", "mensaje": "El número de co...  
84  {codigo": "GN23C", "mensaje": "El número de co...  

[85 rows x 6 columns]

In [6]:
import numpy as np

In [7]:
lista = [1,2,3,4,5,6,78]

In [8]:
lista

[1, 2, 3, 4, 5, 6, 78]

In [9]:
type(lista)

list

In [10]:
array = np.array(lista)

In [11]:
array

array([ 1,  2,  3,  4,  5,  6, 78])

In [12]:
type(array)

numpy.ndarray

In [13]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
type(matriz)

list

In [16]:
array

array([ 1,  2,  3,  4,  5,  6, 78])

In [17]:
array[0]

1

In [18]:
array[1] + array[4]

7

In [19]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
matriz[0]

[1, 2, 3]

In [21]:
matriz[1]

[4, 5, 6]

In [22]:
matriz[0,2]

TypeError: list indices must be integers or slices, not tuple

In [23]:
matriz[0,1]

TypeError: list indices must be integers or slices, not tuple

In [24]:
matriz[1,1]

TypeError: list indices must be integers or slices, not tuple

In [25]:
array

array([ 1,  2,  3,  4,  5,  6, 78])

In [26]:
array[0:3]

array([1, 2, 3])

In [27]:
array[0:5]

array([1, 2, 3, 4, 5])

In [28]:
array[::-1]

array([78,  6,  5,  4,  3,  2,  1])

In [29]:
array[::3]

array([ 1,  4, 78])

In [30]:
matriz[1:]

[[4, 5, 6], [7, 8, 9]]

In [31]:
matriz[::-1]

[[7, 8, 9], [4, 5, 6], [1, 2, 3]]

In [32]:
matriz[1:,0:2]

TypeError: list indices must be integers or slices, not tuple

In [33]:
type(matriz)

list