In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,2))

In [3]:
arr

array([[9, 7],
       [5, 4],
       [6, 6]])

In [4]:
arr.shape

(3, 2)

In [7]:
arr.reshape(1,6)

array([[9, 7, 5, 4, 6, 6]])

In [8]:
arr.reshape(2,3)

array([[9, 7, 5],
       [4, 6, 6]])

In [9]:
arr

array([[9, 7],
       [5, 4],
       [6, 6]])

In [10]:
np.reshape(arr,(2,3), 'F')

array([[9, 6, 4],
       [5, 7, 6]])

In [11]:
np.reshape(arr,(2,3), 'c')

array([[9, 7, 5],
       [4, 6, 6]])

In [12]:
np.reshape(arr,(2,3), 'A')

array([[9, 7, 5],
       [4, 6, 6]])